.TH "/home/gabriel/Templates/StereoVision/Bin Directory Reference" 3 "Wed Apr 2 2014" "Version 0.1" "StereoVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gabriel/Templates/StereoVision/Bin Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCMakeFiles\fP"
.br
.in -1c
