.TH "/home/gabriel/Templates/StereoVision/Source/Application.cpp" 3 "Wed Apr 2 2014" "Version 0.1" "StereoVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gabriel/Templates/StereoVision/Source/Application.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SV/Application\&.hpp>\fP
.br
\fC#include <SV/CameraCalibration\&.hpp>\fP
.br
\fC#include <SV/CameraCapture\&.hpp>\fP
.br
\fC#include <SV/CameraConfiguration\&.hpp>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StereoVision from the source code\&.
