.TH "Application" 3 "Wed Apr 2 2014" "Version 0.1" "StereoVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Application\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApplication\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file Application\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Application::Application ()"

.PP
Definition at line 13 of file Application\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Application::run ()"

.PP
Definition at line 28 of file Application\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StereoVision from the source code\&.
