.TH "/home/gabriel/Templates/StereoVision/Source/CameraCapture.cpp" 3 "Wed Apr 2 2014" "Version 0.1" "StereoVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gabriel/Templates/StereoVision/Source/CameraCapture.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SV/CameraCapture\&.hpp>\fP
.br
\fC#include <SV/Utility\&.hpp>\fP
.br
\fC#include <pylon/InstantCamera\&.h>\fP
.br
\fC#include <pylon/GrabResultPtr\&.h>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <opencv2/calib3d/calib3d\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmCalibrationMatricesNames\fP ({'Q','mx1','my1','mx2','my2'})"
.br
.ti -1c
.RI "\fBmPatternSize\fP ()"
.br
.ti -1c
.RI "\fBmStereoPhotoPtr\fP (stereoPhotoPtr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "mCalibrationMatricesNames ({'Q','mx1','my1','mx2','my2'})"

.SS "mPatternSize ()"

.SS "mStereoPhotoPtr (stereoPhotoPtr)"

.PP
Definition at line 26 of file CameraCapture\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for StereoVision from the source code\&.
