.TH "/home/gabriel/Templates/StereoVision/Source/Main.cpp" 3 "Wed Apr 2 2014" "Version 0.1" "StereoVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gabriel/Templates/StereoVision/Source/Main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SV/Application\&.hpp>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 7 of file Main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for StereoVision from the source code\&.
