.TH "/home/gabriel/Templates/StereoVision/Modules/StereoCalibration/StereoCalibration.cpp" 3 "Wed Apr 2 2014" "Version 0.1" "StereoVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/gabriel/Templates/StereoVision/Modules/StereoCalibration/StereoCalibration.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cv\&.h'\fP
.br
\fC#include 'cxmisc\&.h'\fP
.br
\fC#include 'highgui\&.h'\fP
.br
\fC#include 'cvaux\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 463 of file StereoCalibration\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for StereoVision from the source code\&.
