.TH "SV::CalibrationPattern" 3 "Wed Apr 2 2014" "Version 0.1" "StereoVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SV::CalibrationPattern \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Utility\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalibrationPattern\fP (unsigned int cornersWidth, unsigned int cornersHeight, float squareSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBw\fP"
.br
.ti -1c
.RI "unsigned int \fBh\fP"
.br
.ti -1c
.RI "float \fBs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file Utility\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SV::CalibrationPattern::CalibrationPattern (unsigned intcornersWidth, unsigned intcornersHeight, floatsquareSize)\fC [inline]\fP"

.PP
Definition at line 34 of file Utility\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int SV::CalibrationPattern::h"

.PP
Definition at line 42 of file Utility\&.hpp\&.
.SS "float SV::CalibrationPattern::s"

.PP
Definition at line 43 of file Utility\&.hpp\&.
.SS "unsigned int SV::CalibrationPattern::w"

.PP
Definition at line 41 of file Utility\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StereoVision from the source code\&.
