.TH "SV::StereoPhoto" 3 "Wed Apr 2 2014" "Version 0.1" "StereoVision" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SV::StereoPhoto \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Utility\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::array< std::string, 2 > \fBcameras\fP"
.br
.ti -1c
.RI "std::pair< cv::Mat, cv::Mat > \fBmatPair\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file Utility\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::array<std::string, 2> SV::StereoPhoto::cameras"

.PP
Definition at line 48 of file Utility\&.hpp\&.
.SS "std::pair<cv::Mat, cv::Mat> SV::StereoPhoto::matPair"

.PP
Definition at line 49 of file Utility\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StereoVision from the source code\&.
